#!/usr/bin/env bash

export SECRET_KEY_BASE=${SECRET_KEY_BASE:-"A long secret"}
export PORT=${PORT:-3000}
export RAILS_ENV=${RAILS_ENV:-production}
export MIN_WORKERS=${MIN_WORKERS:-2}
export MAX_WORKERS=${MAX_WORKERS:-2}

bundle exec rake db:create db:migrate db:seed assets:precompile

# Puma
# bundle exec puma -C config/puma.rb

# Passenger
bundle exec passenger start -p $PORT -e $RAILS_ENV --min-instances $MIN_WORKERS --max-pool-size $MAX_WORKERS
