#!/usr/bin/env bash

export SECRET_KEY_BASE=$(bundle exec rake secret)
export PORT=${PORT:-3000}
export RAILS_ENV=${RAILS_ENV:-production}
export MIN_WORKERS=${MIN_WORKERS:-2}
export MAX_WORKERS=${MAX_WORKERS:-2}

bundle exec rake db:create db:migrate db:seed assets:precompile
bundle exec puma -C config/puma.rb
